<?php
return [
   "error404" => ["enabled" => true, "public" => true, "hasView" => true],
   "atletas" => ["enabled" => true, "public" => false, "hasView" => true],
   "asistencias" => ["enabled" => true, "public" => false, "hasView" => true],
   "bitacora" => ["enabled" => true, "public" => false, "hasView" => true],
   "categorias" => ["enabled" => true, "public" => false, "hasView" => false],
   "logout" => ["enabled" => true, "public" => false, "hasView" => true],
   "dashboard" => ["enabled" => true, "public" => false, "hasView" => true],
   "entrenadores" => ["enabled" => true, "public" => false, "hasView" => true],
   "eventos" => ["enabled" => true, "public" => false, "hasView" => true],
   "faq" => ["enabled" => true, "public" => true, "hasView" => true],
   "landing" => ["enabled" => true, "public" => true, "hasView" => true],
   "login" => ["enabled" => true, "public" => true, "hasView" => true],
   "manual" => ["enabled" => true, "public" => false, "hasView" => true],
   "mensualidad" => ["enabled" => true, "public" => false, "hasView" => true],
   "notificaciones" => ["enabled" => true, "public" => false, "hasView" => true],
   "perfilatleta" => ["enabled" => true, "public" => true, "hasView" => true],
   "recovery" => ["enabled" => true, "public" => false, "hasView" => true],
   "reestablecer" => ["enabled" => true, "public" => false, "hasView" => true],
   "reportes" => ["enabled" => true, "public" => false, "hasView" => true],
   "rolespermisos" => ["enabled" => true, "public" => false, "hasView" => true],
   "subs" => ["enabled" => true, "public" => false, "hasView" => false],
   "tipoatleta" => ["enabled" => true, "public" => false, "hasView" => false],
   "tipocompetencia" => ["enabled" => true, "public" => false, "hasView" => false],
   "wada" => ["enabled" => true, "public" => false, "hasView" => true]
];
